### ISSUE TITLE
The filters of SFANC and GFANC

### ISSUE THREAD

**Issue by gold90123** [Luo-Zhengding/Generative-Fixed-filter-Active-Noise-Control-based-on-Deep-Learning#1]
Hi there,

First of all, I want to express my appreciation for your work on SFANC-FxNLMS and GFANC. It's inspiring to see someone working on open-source ANC systems, and your assistance has been incredibly helpful to me.

However, I have encountered a question that I am struggling to understand. Both SFANC and GFANC utilize the Control_filter_selection() function to generate the filters that SFANC and GFANC required (e.g., 10 filters for a 10-second duration). But, during the actual SFANC and GFANC stages, only 9 filters are utilized. This discrepancy arises because the first-second noise uses the filter that are entirely composed of zeros, and the rest of "i" second noise uses the "i - 1"th filter, and nobody utilize the last filter. I am puzzled as to why the "i" second noise cannot use the "i"th filter directly.

In the GFANC paper, it is mentioned that:
"However, GFANC and SFANC cannot handle the first-second noise because they update the control filter coefficients for the next second based on the first-second noise."

However, in the program, I haven't come across any code segment that explicitly updates the control filter coefficients based on the first-second noise. Instead, the control filter coefficients appear to be switched to self.Filter_vector[j] at the end of each second.

Could you please help clarify this discrepancy for me? I am eager to gain a better understanding of how the control filter coefficients are updated in SFANC-FxNLMS and GFANC. Thank you in advance for your assistance.

**Comment by Luo-Zhengding** [comment]
Thank you for your interest in our ANC works.

Since ANC is a real-time demanding task, we use the control filter obtained from the current frame for noise reduction for the next frame, and we cannot use the current control filter for noise reduction for the current frame, because the noise is passing all the time and cannot be passed in repeatedly for noise reduction.
________________________________
发件人: Goldwin ***@***.***>
发送时间: 2023年7月21日 22:34
收件人: Luo-Zhengding/GFANC-Generative-fixed-filter-active-noise-control ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Luo-Zhengding/GFANC-Generative-fixed-filter-active-noise-control] The filters of SFANC and GFANC (Issue #1)


Hi there,

First of all, I want to express my appreciation for your work on SFANC-FxNLMS and GFANC. It's inspiring to see someone working on open-source ANC systems, and your assistance has been incredibly helpful to me.

However, I have encountered a question that I am struggling to understand. Both SFANC and GFANC utilize the Control_filter_selection() function to generate the filters that SFANC and GFANC required (e.g., 10 filters for a 10-second duration). But, during the actual SFANC and GFANC stages, only 9 filters are utilized. This discrepancy arises because the first-second noise uses the filter that are entirely composed of zeros, and the rest of "i" second noise uses the "i - 1"th filter, and nobody utilize the last filter. I am puzzled as to why the "i" second noise cannot use the "i"th filter directly.

In the GFANC paper, it is mentioned that:
"However, GFANC and SFANC cannot handle the first-second noise because they update the control filter coefficients for the next second based on the first-second noise."

However, in the program, I haven't come across any code segment that explicitly updates the control filter coefficients based on the first-second noise. Instead, the control filter coefficients appear to be switched to self.Filter_vector[j] at the end of each second.

Could you please help clarify this discrepancy for me? I am eager to gain a better understanding of how the control filter coefficients are updated in SFANC-FxNLMS and GFANC. Thank you in advance for your assistance.

―

**Comment by gold90123** [comment]
Thanks for providing such a clear explanation. I now understand the real-time demands of ANC and why the current control filter cannot be used for noise reduction in the same frame. Your insights have been immensely helpful to me.

I truly appreciate your assistance and wish you a wonderful day ahead.
